### ISSUE TITLE
Hashing the API token (like Laravel Sanctum) before storing it in the database

### ISSUE THREAD

**Issue by mwllgr** [givebutter/laravel-keyable#12]
Hello,

because the tokens are pretty much passwords, Laravel Sanctum hashes tokens before saving them to the database in the following format: `<id>|<token>` - the ID is there for finding the token faster (by primary key lookup).

Here's their implementation for creating a new token, as seen in [HasApiTokens.php (line 46)](https://github.com/laravel/sanctum/blob/21676ec103ee074dcdf7385af978ee97c4543111/src/HasApiTokens.php#L46)
```php
    public function createToken(string $name, array $abilities = ['*'], DateTimeInterface $expiresAt = null)
    {
        $token = $this->tokens()->create([
            'name' => $name,
            'token' => hash('sha256', $plainTextToken = Str::random(40)),
            'abilities' => $abilities,
            'expires_at' => $expiresAt,
        ]);

        return new NewAccessToken($token, $token->getKey().'|'.$plainTextToken);
    }
```

... and here's the way they check it in [PersonalAccessToken.php (line 58)](https://github.com/laravel/sanctum/blob/21676ec103ee074dcdf7385af978ee97c4543111/src/PersonalAccessToken.php#L58):
```php
public static function findToken($token)
    {
        if (strpos($token, '|') === false) {
            return static::where('token', hash('sha256', $token))->first();
        }

        [$id, $token] = explode('|', $token, 2);

        if ($instance = static::find($id)) {
            return hash_equals($instance->token, hash('sha256', $token)) ? $instance : null;
        }
    }
```

I think it'd be a great idea for laravel-keyable to do the same thing. The user would receive a plainTextToken which can only be displayed once.

**Comment by liran-co** [comment]
This will be added in the next release shortly, thanks for the suggestion.
