### ISSUE TITLE
[SUPPORT] Support for UUID

### ISSUE THREAD

**Issue by soulcodex** [givebutter/laravel-keyable#3]
Hi my friend,

Currently too many apps have needs manage big sets of data and a big integer primary key in many scenarios represent a big collision risk.

Taking in count the big integer limitations like primary key when you have a millions of rows

Do you have planned implement or support UUID in this package or could be more faster making a pull request with this changes implemented and with the correct dependencies in your composer file

Thanks

**Comment by liran-co** [comment]
Related to: https://github.com/givebutter/laravel-keyable/pull/4
